### ISSUE TITLE
Cannot read property 'ui' of undefined

### ISSUE THREAD

**Issue by fank** [gstack/calculator#2]
[Enter steps to reproduce below:]
1. Open atom
2. Open the command palette
3. Type "calc"
4. Select "Calculator: Toggle"
5. And the error popup will appear

**Atom Version**: 0.210.0
**System**: Ubuntu 15.04
**Thrown From**: [calculator](https://github.com/gstack/calculator) package, v0.1.0
### Stack Trace

Failed to activate the calculator package

```
At Cannot read property 'ui' of undefined

TypeError: Cannot read property 'ui' of undefined
  at /home/user/.atom/packages/calculator/jquery-ui.js:33:9
  at $.ui (/home/user/.atom/packages/calculator/jquery-ui.js:17:3)
  at module.exports (/home/user/.atom/packages/calculator/jquery-ui.js:19:2)
  at Object.<anonymous> (/home/user/.atom/packages/calculator/lib/calculator.coffee:6:8)
  at Object.<anonymous> (/home/user/.atom/packages/calculator/lib/calculator.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:236:14)
  at /usr/share/atom/resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:219:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:03.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 calculator:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "snippets",
      "linter-perl",
      "atom-auto-uglify",
      "save-session",
      "highlight-selected",
      "minimap-highlight-selected",
      "atom-2048",
      "achievements"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
calculator, v0.1.0
color-picker, v2.0.7
default-language, v0.1.3
docblockr, v0.7.2
git-log, v0.4.1
git-tab-status, v1.9.2
html-entities, v0.4.0
language-mason, v2.0.4
language-perl, v0.25.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-lua, v0.1.6
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-selection, v4.2.0
set-syntax, v0.3.0
tabs-to-spaces, v0.11.0
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by fank** [comment]
Duplicate of #3
