### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ui' of undefined

### ISSUE THREAD

**Issue by rokyed** [gstack/calculator#3]
[Enter steps to reproduce below:]
1. Install the app
2. Admire the crash 

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [calculator](https://github.com/gstack/calculator) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'ui' of undefined

```
At /Users/rokyed/.atom/packages/calculator/jquery-ui.js:33

TypeError: Cannot read property 'ui' of undefined
  at /Users/rokyed/.atom/packages/calculator/jquery-ui.js:33:9
  at $.ui (/Users/rokyed/.atom/packages/calculator/jquery-ui.js:17:3)
  at module.exports (/Users/rokyed/.atom/packages/calculator/jquery-ui.js:19:2)
  at Object.<anonymous> (/Users/rokyed/.atom/packages/calculator/lib/calculator.coffee:6:8)
  at Object.<anonymous> (/Users/rokyed/.atom/packages/calculator/lib/calculator.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
 11x -3:28.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:57.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:57 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 39x -2:56 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:59.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:59.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 11x -0:58.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:54.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:53.2.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:51.8.0 core:undo (atom-text-editor.editor.is-focused)
  8x -0:49.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 19x -0:42.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "language-java"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
git-diff-details, v0.18.0
git-log, v0.4.1
minimap, v4.10.0
pigments, v0.8.1

# Dev
No dev packages
```

**Comment by julkue** [comment]
I laugh that this is still open

**Comment by elistone** [comment]
+1

**Comment by XxLMM13xXgaming** [comment]
I got this too

**Comment by fantonangeli** [comment]
+1

**Comment by ravenroc** [comment]
And it's still here. +1

**Comment by pedro-rivera** [comment]
and the saga is still here

**Comment by luisrayas3** [comment]
+1
