### ISSUE TITLE
Failed to activate the calculator package

### ISSUE THREAD

**Issue by jorgefuertes** [gstack/calculator#4]
[Enter steps to reproduce below:]
1. Click on Packages > Calculator > Toggle

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [calculator](https://github.com/gstack/calculator) package, v0.1.0
### Stack Trace

Failed to activate the calculator package

```
At Cannot read property 'ui' of undefined

TypeError: Cannot read property 'ui' of undefined
    at /Users/queru/.atom/packages/calculator/jquery-ui.js:33:9
    at $.ui (/Users/queru/.atom/packages/calculator/jquery-ui.js:17:3)
    at module.exports (/Users/queru/.atom/packages/calculator/jquery-ui.js:19:2)
    at Object.<anonymous> (/Users/queru/.atom/packages/calculator/lib/calculator.coffee:9:33)
    at Object.<anonymous> (/Users/queru/.atom/packages/calculator/lib/calculator.coffee:49:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
     -0:00.6.0 calculator:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "Sass-Syntax-Highlight",
      "Atom-Syntax-highlighting-for-Sass",
      "minimap"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-sass, v0.1.0
block-cursor, v0.13.1
calculator, v0.1.0
color-picker, v2.0.10
highlight-column, v0.5.0
make-coffee, v0.1.1
pigments, v0.8.4
project-manager, v1.15.11
ruby-slim, v0.2.0
slim-language, v2.2.0

# Dev
No dev packages
```

**Comment by brucehvn** [comment]
Getting this on Ubuntu 14.04 as well.

**Comment by jorgefuertes** [comment]
Still fails in OS-X.
